name: test

on:
  workflow_dispatch:
    inputs:
        commit:
          description: 'commit'
          required: true
          type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
