name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.sha }}
      - run: git log
